import type { InventoryItem, InventorySummary, PurchaseOrder } from './types';

const allInventoryItems: InventoryItem[] = [
  {
    id: 'inv-001',
    partId: 'part-br-001',
    partNumber: 'KC-BP-900T-2018',
    partName: 'Brake Pad Set (Hoist) — Konecranes 900T',
    partName_ko: '브레이크 패드 세트 (호이스트) — Konecranes 900T',
    category: 'brake',
    criticality: 'critical',
    manufacturer: 'Konecranes',
    unitPrice: 480,
    currentQty: 4,
    reservedQty: 1,
    availableQty: 3,
    minStockQty: 4,
    reorderPoint: 5,
    status: 'low',
    lastReceiptDate: '2026-01-15',
    lastIssueDate: '2026-04-14',
    locationBin: 'A-01-03',
    leadTimeDays: 21,
  },
  {
    id: 'inv-002',
    partId: 'part-wr-001',
    partNumber: 'WR-36MM-6X37-BRIDON',
    partName: 'Wire Rope 36mm 6x37 (200m) — Main Hoist',
    partName_ko: '와이어 로프 36mm 6x37 (200m) — 주 호이스트',
    category: 'wire_rope',
    criticality: 'critical',
    manufacturer: 'Bridon',
    unitPrice: 2200,
    currentQty: 3,
    reservedQty: 0,
    availableQty: 3,
    minStockQty: 2,
    reorderPoint: 3,
    status: 'normal',
    lastReceiptDate: '2025-11-20',
    lastIssueDate: '2026-03-10',
    locationBin: 'B-02-01',
    leadTimeDays: 35,
  },
  {
    id: 'inv-003',
    partId: 'part-wr-002',
    partNumber: 'WR-28MM-6X37-BRIDON',
    partName: 'Wire Rope 28mm 6x37 (200m) — Aux Hoist',
    partName_ko: '와이어 로프 28mm 6x37 (200m) — 보조 호이스트',
    category: 'wire_rope',
    criticality: 'critical',
    manufacturer: 'Bridon',
    unitPrice: 1850,
    currentQty: 1,
    reservedQty: 0,
    availableQty: 1,
    minStockQty: 2,
    reorderPoint: 3,
    status: 'low',
    lastReceiptDate: '2025-09-05',
    lastIssueDate: '2026-04-10',
    locationBin: 'B-02-02',
    leadTimeDays: 35,
  },
  {
    id: 'inv-004',
    partId: 'part-plc-001',
    partNumber: 'SIEMENS-S7-1500-CPU',
    partName: 'PLC CPU Module (Siemens S7-1500)',
    partName_ko: 'PLC CPU 모듈 (Siemens S7-1500)',
    category: 'electrical',
    criticality: 'critical',
    manufacturer: 'Siemens',
    unitPrice: 3200,
    currentQty: 2,
    reservedQty: 0,
    availableQty: 2,
    minStockQty: 1,
    reorderPoint: 2,
    status: 'normal',
    lastReceiptDate: '2025-12-01',
    lastIssueDate: '2026-04-13',
    locationBin: 'C-01-05',
    leadTimeDays: 45,
  },
  {
    id: 'inv-005',
    partId: 'part-seal-001',
    partNumber: 'SEAL-OSK-75MM',
    partName: 'Output Shaft Oil Seal 75mm',
    partName_ko: '출력축 오일씰 75mm',
    category: 'seal_gasket',
    criticality: 'essential',
    manufacturer: 'SKF',
    unitPrice: 45,
    currentQty: 12,
    reservedQty: 2,
    availableQty: 10,
    minStockQty: 6,
    reorderPoint: 8,
    status: 'normal',
    lastReceiptDate: '2026-02-10',
    lastIssueDate: '2026-04-14',
    locationBin: 'A-03-07',
    leadTimeDays: 14,
  },
  {
    id: 'inv-006',
    partId: 'part-oil-001',
    partNumber: 'MOBIL-GLYGOYLE-460-20L',
    partName: 'Gear Oil Mobil Glygoyle 460 (20L)',
    partName_ko: '기어 오일 Mobil Glygoyle 460 (20L)',
    category: 'lubricant',
    criticality: 'standard',
    manufacturer: 'Mobil',
    unitPrice: 120,
    currentQty: 8,
    reservedQty: 1,
    availableQty: 7,
    minStockQty: 5,
    reorderPoint: 6,
    status: 'normal',
    lastReceiptDate: '2026-03-01',
    lastIssueDate: '2026-04-14',
    locationBin: 'D-01-02',
    leadTimeDays: 7,
  },
  {
    id: 'inv-007',
    partId: 'part-inv-001',
    partNumber: 'KC-INV-160KW-2019',
    partName: 'Hoist Inverter 160kW — Konecranes',
    partName_ko: '호이스트 인버터 160kW — Konecranes',
    category: 'electrical',
    criticality: 'critical',
    manufacturer: 'Konecranes',
    unitPrice: 8500,
    currentQty: 0,
    reservedQty: 0,
    availableQty: 0,
    minStockQty: 1,
    reorderPoint: 1,
    status: 'out_of_stock',
    lastReceiptDate: '2025-06-20',
    lastIssueDate: '2025-10-15',
    locationBin: 'C-02-01',
    leadTimeDays: 60,
  },
  {
    id: 'inv-008',
    partId: 'part-bearing-001',
    partNumber: 'SKF-22340-CCK-W33',
    partName: 'Spherical Roller Bearing SKF 22340',
    partName_ko: '구면 롤러 베어링 SKF 22340',
    category: 'gear_bearing',
    criticality: 'essential',
    manufacturer: 'SKF',
    unitPrice: 680,
    currentQty: 6,
    reservedQty: 0,
    availableQty: 6,
    minStockQty: 4,
    reorderPoint: 5,
    status: 'normal',
    lastReceiptDate: '2026-01-08',
    lastIssueDate: '2026-02-20',
    locationBin: 'A-02-04',
    leadTimeDays: 28,
  },
  {
    id: 'inv-009',
    partId: 'part-cable-001',
    partNumber: 'CAB-COMM-SET-LH',
    partName: 'Communication Cable Set — Liebherr EOT',
    partName_ko: '통신 케이블 세트 — Liebherr EOT',
    category: 'electrical',
    criticality: 'essential',
    manufacturer: 'Liebherr',
    unitPrice: 180,
    currentQty: 3,
    reservedQty: 0,
    availableQty: 3,
    minStockQty: 2,
    reorderPoint: 3,
    status: 'normal',
    lastReceiptDate: '2025-10-14',
    lastIssueDate: '2026-04-13',
    locationBin: 'C-01-08',
    leadTimeDays: 30,
  },
  {
    id: 'inv-010',
    partId: 'part-ls-001',
    partNumber: 'LS-HOIST-UPPER-KC',
    partName: 'Hoist Upper Limit Switch — Konecranes',
    partName_ko: '호이스트 상부 리밋 스위치 — Konecranes',
    category: 'sensor',
    criticality: 'critical',
    manufacturer: 'Konecranes',
    unitPrice: 220,
    currentQty: 2,
    reservedQty: 0,
    availableQty: 2,
    minStockQty: 3,
    reorderPoint: 4,
    status: 'low',
    lastReceiptDate: '2025-08-30',
    lastIssueDate: '2026-01-15',
    locationBin: 'C-03-02',
    leadTimeDays: 21,
  },
];

const allPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-001',
    poNumber: 'PO-2026-0012',
    vendor: 'Konecranes Parts & Service',
    orderDate: '2026-04-14',
    expectedDelivery: '2026-05-05',
    items: [
      { partId: 'part-inv-001', partName: 'Hoist Inverter 160kW', qty: 1, unitPrice: 8500, total: 8500 },
      { partId: 'part-br-001', partName: 'Brake Pad Set (Hoist)', qty: 4, unitPrice: 480, total: 1920 },
    ],
    totalAmount: 10420,
    status: 'ordered',
    urgency: 'urgent',
    requester: '조범희',
  },
  {
    id: 'po-002',
    poNumber: 'PO-2026-0011',
    vendor: 'Bridon International',
    orderDate: '2026-04-10',
    expectedDelivery: '2026-05-15',
    items: [
      { partId: 'part-wr-002', partName: 'Wire Rope 28mm 6x37 (200m)', qty: 2, unitPrice: 1850, total: 3700 },
    ],
    totalAmount: 3700,
    status: 'in_transit',
    urgency: 'normal',
    requester: '박순영',
  },
  {
    id: 'po-003',
    poNumber: 'PO-2026-0010',
    vendor: 'SKF Korea',
    orderDate: '2026-04-05',
    expectedDelivery: '2026-04-19',
    items: [
      { partId: 'part-ls-001', partName: 'Hoist Upper Limit Switch', qty: 4, unitPrice: 220, total: 880 },
      { partId: 'part-seal-001', partName: 'Output Shaft Oil Seal 75mm', qty: 10, unitPrice: 45, total: 450 },
    ],
    totalAmount: 1330,
    status: 'in_transit',
    urgency: 'normal',
    requester: '정종민',
  },
];

export function getAllInventoryItems(): InventoryItem[] {
  return allInventoryItems;
}

export function getAllPurchaseOrders(): PurchaseOrder[] {
  return allPurchaseOrders;
}

export function getInventorySummary(): InventorySummary {
  const totalValue = allInventoryItems.reduce(
    (sum, item) => sum + item.currentQty * item.unitPrice,
    0,
  );
  return {
    totalParts: allInventoryItems.length,
    lowStock: allInventoryItems.filter((i) =>
      ['low', 'out_of_stock'].includes(i.status),
    ).length,
    reorderNeeded: allInventoryItems.filter(
      (i) => i.availableQty <= i.reorderPoint,
    ).length,
    activePOs: allPurchaseOrders.filter((p) =>
      ['ordered', 'in_transit', 'approved'].includes(p.status),
    ).length,
    totalValue,
  };
}
