import type {
  MonitoringLiveTableColumnPreset,
  MonitoringLiveTablePreset,
} from './types';

const DEFAULT_GROUPS = [
  {
    key: 'load',
    labelKey: 'common:craneStatus.table.groups.load',
    defaultLabel: 'Load',
  },
] satisfies MonitoringLiveTablePreset['groups'];

const DEFAULT_COLUMNS = [
  {
    tagDefinitionId: 7,
    groupKey: 'load',
    headerLabelKey: 'common:craneStatus.table.columns.mh1Weight',
    shortLabel: 'MH#1 Load',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 8,
    groupKey: 'load',
    headerLabelKey: 'common:craneStatus.table.columns.mh2Weight',
    shortLabel: 'MH#2 Load',
    cellKind: 'numeric',
    align: 'center',
  },
] satisfies MonitoringLiveTableColumnPreset[];

const DOCK_IN_GROUPS = [
  {
    key: 'systemStatus',
    labelKey: 'common:craneStatus.table.groups.systemStatus',
    defaultLabel: 'System Status',
  },
  {
    key: 'motionStatus',
    labelKey: 'common:craneStatus.table.groups.motionStatus',
    defaultLabel: 'Motion Status',
  },
  {
    key: 'load',
    labelKey: 'common:craneStatus.table.groups.load',
    defaultLabel: 'Load',
  },
  {
    key: 'height',
    labelKey: 'common:craneStatus.table.groups.height',
    defaultLabel: 'Height',
  },
  {
    key: 'distance',
    labelKey: 'common:craneStatus.table.groups.distance',
    defaultLabel: 'Distance',
  },
  {
    key: 'gearDistance',
    labelKey: 'common:craneStatus.table.groups.gearDistance',
    defaultLabel: 'Gear Distance',
  },
] satisfies MonitoringLiveTablePreset['groups'];

const DOCK_IN_COLUMNS = [
  {
    tagDefinitionId: 29,
    groupKey: 'systemStatus',
    headerLabelKey: 'common:craneStatus.table.columns.heartbeat',
    shortLabel: 'Heartbeat',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 30,
    groupKey: 'systemStatus',
    headerLabelKey: 'common:craneStatus.table.columns.controlOn',
    shortLabel: 'Control',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 31,
    groupKey: 'systemStatus',
    headerLabelKey: 'common:craneStatus.table.columns.systemError',
    shortLabel: 'System Err',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'negativeWhenTrue',
  },
  {
    tagDefinitionId: 32,
    groupKey: 'systemStatus',
    headerLabelKey: 'common:craneStatus.table.columns.inverterError',
    shortLabel: 'Invert Err',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'negativeWhenTrue',
  },
  {
    tagDefinitionId: 33,
    groupKey: 'systemStatus',
    headerLabelKey: 'common:craneStatus.table.columns.accsBypass',
    shortLabel: 'ACCS By',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'warningWhenTrue',
  },
  {
    tagDefinitionId: 34,
    groupKey: 'systemStatus',
    headerLabelKey: 'common:craneStatus.table.columns.accsOff',
    shortLabel: 'ACCS Off',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'negativeWhenTrue',
  },
  {
    tagDefinitionId: 35,
    groupKey: 'systemStatus',
    headerLabelKey: 'common:craneStatus.table.columns.emergencyStop',
    shortLabel: 'E-Stop',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'negativeWhenTrue',
  },
  {
    tagDefinitionId: 36,
    groupKey: 'systemStatus',
    headerLabelKey: 'common:craneStatus.table.columns.remoteAck',
    shortLabel: 'Remote Ack',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 45,
    groupKey: 'motionStatus',
    headerLabelKey: 'common:craneStatus.table.columns.mh1Status',
    shortLabel: 'MH#1',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 46,
    groupKey: 'motionStatus',
    headerLabelKey: 'common:craneStatus.table.columns.mh2Status',
    shortLabel: 'MH#2',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 47,
    groupKey: 'motionStatus',
    headerLabelKey: 'common:craneStatus.table.columns.mh3Status',
    shortLabel: 'MH#3',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 48,
    groupKey: 'motionStatus',
    headerLabelKey: 'common:craneStatus.table.columns.ah1Status',
    shortLabel: 'AH#1',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 49,
    groupKey: 'motionStatus',
    headerLabelKey: 'common:craneStatus.table.columns.ah2Status',
    shortLabel: 'AH#2',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 50,
    groupKey: 'motionStatus',
    headerLabelKey: 'common:craneStatus.table.columns.ts1Status',
    shortLabel: 'TS#1',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 51,
    groupKey: 'motionStatus',
    headerLabelKey: 'common:craneStatus.table.columns.ts2Status',
    shortLabel: 'TS#2',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 52,
    groupKey: 'motionStatus',
    headerLabelKey: 'common:craneStatus.table.columns.ts3Status',
    shortLabel: 'TS#3',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 53,
    groupKey: 'motionStatus',
    headerLabelKey: 'common:craneStatus.table.columns.tlStatus',
    shortLabel: 'TL',
    cellKind: 'statusDot',
    align: 'center',
    statusBehavior: 'positiveWhenTrue',
  },
  {
    tagDefinitionId: 7,
    groupKey: 'load',
    headerLabelKey: 'common:craneStatus.table.columns.mh1Weight',
    shortLabel: 'MH#1',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 8,
    groupKey: 'load',
    headerLabelKey: 'common:craneStatus.table.columns.mh2Weight',
    shortLabel: 'MH#2',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 9,
    groupKey: 'load',
    headerLabelKey: 'common:craneStatus.table.columns.mh3Weight',
    shortLabel: 'MH#3',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 10,
    groupKey: 'load',
    headerLabelKey: 'common:craneStatus.table.columns.ah1Weight',
    shortLabel: 'AH#1',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 11,
    groupKey: 'load',
    headerLabelKey: 'common:craneStatus.table.columns.ah2Weight',
    shortLabel: 'AH#2',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 12,
    groupKey: 'height',
    headerLabelKey: 'common:craneStatus.table.columns.mh1Height',
    shortLabel: 'MH#1',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 13,
    groupKey: 'height',
    headerLabelKey: 'common:craneStatus.table.columns.mh2Height',
    shortLabel: 'MH#2',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 14,
    groupKey: 'height',
    headerLabelKey: 'common:craneStatus.table.columns.mh3Height',
    shortLabel: 'MH#3',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 15,
    groupKey: 'height',
    headerLabelKey: 'common:craneStatus.table.columns.ah1Height',
    shortLabel: 'AH#1',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 16,
    groupKey: 'height',
    headerLabelKey: 'common:craneStatus.table.columns.ah2Height',
    shortLabel: 'AH#2',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 17,
    groupKey: 'distance',
    headerLabelKey: 'common:craneStatus.table.columns.ts1Distance',
    shortLabel: 'TS#1',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 18,
    groupKey: 'distance',
    headerLabelKey: 'common:craneStatus.table.columns.ts2Distance',
    shortLabel: 'TS#2',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 19,
    groupKey: 'distance',
    headerLabelKey: 'common:craneStatus.table.columns.ts3Distance',
    shortLabel: 'TS#3',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 20,
    groupKey: 'distance',
    headerLabelKey: 'common:craneStatus.table.columns.tlDistance',
    shortLabel: 'TL',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 21,
    groupKey: 'gearDistance',
    headerLabelKey: 'common:craneStatus.table.columns.tsStopGearDistance',
    shortLabel: 'TS Stop',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 22,
    groupKey: 'gearDistance',
    headerLabelKey: 'common:craneStatus.table.columns.tsGear1Distance',
    shortLabel: 'TS G1',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 23,
    groupKey: 'gearDistance',
    headerLabelKey: 'common:craneStatus.table.columns.tsGear2Distance',
    shortLabel: 'TS G2',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 24,
    groupKey: 'gearDistance',
    headerLabelKey: 'common:craneStatus.table.columns.tsGear3Distance',
    shortLabel: 'TS G3',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 25,
    groupKey: 'gearDistance',
    headerLabelKey: 'common:craneStatus.table.columns.tlStopGearDistance',
    shortLabel: 'TL Stop',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 26,
    groupKey: 'gearDistance',
    headerLabelKey: 'common:craneStatus.table.columns.tlGear1Distance',
    shortLabel: 'TL G1',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 27,
    groupKey: 'gearDistance',
    headerLabelKey: 'common:craneStatus.table.columns.tlGear2Distance',
    shortLabel: 'TL G2',
    cellKind: 'numeric',
    align: 'center',
  },
  {
    tagDefinitionId: 28,
    groupKey: 'gearDistance',
    headerLabelKey: 'common:craneStatus.table.columns.tlGear3Distance',
    shortLabel: 'TL G3',
    cellKind: 'numeric',
    align: 'center',
  },
] satisfies MonitoringLiveTableColumnPreset[];

const MONITORING_LIVE_TABLE_PRESETS: Record<string, MonitoringLiveTablePreset> =
  {
    'dock-1': {
      groups: DEFAULT_GROUPS,
      columns: DEFAULT_COLUMNS,
    },
    'dock-2': {
      groups: DEFAULT_GROUPS,
      columns: DEFAULT_COLUMNS,
    },
    goliath: {
      groups: DEFAULT_GROUPS,
      columns: DEFAULT_COLUMNS,
    },
    'dock-in': {
      groups: DOCK_IN_GROUPS,
      columns: DOCK_IN_COLUMNS,
    },
  };

const FALLBACK_PRESET: MonitoringLiveTablePreset = {
  groups: DEFAULT_GROUPS,
  columns: DEFAULT_COLUMNS,
};

export function getMonitoringLiveTablePreset(regionId: string) {
  return MONITORING_LIVE_TABLE_PRESETS[regionId] ?? FALLBACK_PRESET;
}

export function getMonitoringLiveTableTagDefinitionIds(regionId: string) {
  return getMonitoringLiveTablePreset(regionId).columns.map(
    (column) => column.tagDefinitionId,
  );
}
