import type { InspectionSummary, InspectionWO } from './types';

const frequentChecklist = [
  { id: 'fi-01', category: 'Fluid & Equipment', category_ko: '유체 및 설비', itemName: 'Oil Leak Check', itemName_ko: '오일 누유 점검', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-02', category: 'Fluid & Equipment', category_ko: '유체 및 설비', itemName: 'Sensor Condition', itemName_ko: '센서 상태 점검', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-03', category: 'Fluid & Equipment', category_ko: '유체 및 설비', itemName: 'Piping Condition', itemName_ko: '배관 상태 점검', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-04', category: 'Key Components', category_ko: '주요 구성품', itemName: 'Shaft & Chain Condition', itemName_ko: '샤프트 및 체인 상태', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-05', category: 'Key Components', category_ko: '주요 구성품', itemName: 'Wire Rope Condition', itemName_ko: '와이어 로프 상태', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-06', category: 'Safety Devices', category_ko: '안전 장치', itemName: 'Brake Operation', itemName_ko: '브레이크 작동 점검', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-07', category: 'Safety Devices', category_ko: '안전 장치', itemName: 'Limit Switch Operation', itemName_ko: '리밋 스위치 작동 점검', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-08', category: 'Safety Devices', category_ko: '안전 장치', itemName: 'E-Stop Function', itemName_ko: '비상 정지 기능 점검', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-09', category: 'Electrical', category_ko: '전기', itemName: 'Controller Check', itemName_ko: '제어기 점검', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-10', category: 'Electrical', category_ko: '전기', itemName: 'Panel Inspection', itemName_ko: '패널 점검', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-11', category: 'Dynamic Check', category_ko: '동적 점검', itemName: 'No-Load Test Run', itemName_ko: '무부하 시운전', judgment: null, actionRequired: 'none' as const },
  { id: 'fi-12', category: 'Dynamic Check', category_ko: '동적 점검', itemName: 'Loaded Test Run', itemName_ko: '부하 시운전', judgment: null, actionRequired: 'none' as const },
];

const allInspectionWOs: InspectionWO[] = [
  {
    id: 'insp-001',
    woNumber: 'INS-2026-0001',
    woType: 'frequent',
    craneId: 'crane-101',
    craneName: 'GC-101',
    siteId: 'dock-1',
    siteName: 'Dock No.1',
    scheduledDate: '2026-04-14',
    actualDate: '2026-04-14',
    assignedTo: '조범희',
    performerType: 'internal',
    status: 'completed',
    priority: 'normal',
    result: 'pass',
    findings: 'All items checked. Minor wear on hoist brake observed.',
    findings_ko: '전 항목 점검 완료. 호이스트 브레이크 경미한 마모 확인.',
    totalHours: 2.5,
    cost: 320,
    checklistItems: frequentChecklist.map((item, i) => ({
      ...item,
      judgment: i === 5 ? 'fail' : 'pass',
      severity: i === 5 ? 'minor' : 'normal',
      comment: i === 5 ? 'Brake pad worn to 60% — schedule replacement within 30 days' : undefined,
      actionRequired: i === 5 ? 'repair_needed' : 'none',
    })),
  },
  {
    id: 'insp-002',
    woNumber: 'INS-2026-0002',
    woType: 'frequent',
    craneId: 'crane-102',
    craneName: 'GC-102',
    siteId: 'dock-1',
    siteName: 'Dock No.1',
    scheduledDate: '2026-04-14',
    actualDate: null,
    assignedTo: '정종민',
    performerType: 'internal',
    status: 'in_progress',
    priority: 'normal',
    result: null,
    checklistItems: frequentChecklist.map((item, i) => ({
      ...item,
      judgment: i < 6 ? 'pass' : null,
    })),
  },
  {
    id: 'insp-003',
    woNumber: 'INS-2026-0003',
    woType: 'periodic',
    craneId: 'crane-103',
    craneName: 'GC-103',
    siteId: 'dock-1',
    siteName: 'Dock No.1',
    scheduledDate: '2026-04-10',
    actualDate: null,
    assignedTo: 'M&S Corp.',
    performerType: 'third_party',
    status: 'overdue',
    priority: 'high',
    result: null,
    checklistItems: frequentChecklist.map((item) => ({ ...item, judgment: null })),
  },
  {
    id: 'insp-004',
    woNumber: 'INS-2026-0004',
    woType: 'frequent',
    craneId: 'crane-201',
    craneName: 'QC-201',
    siteId: 'dock-2',
    siteName: 'Dock No.2',
    scheduledDate: '2026-04-13',
    actualDate: '2026-04-13',
    assignedTo: '박순영',
    performerType: 'internal',
    status: 'completed',
    priority: 'normal',
    result: 'pass',
    findings: 'Normal condition. All safety devices operational.',
    findings_ko: '정상 상태. 모든 안전 장치 정상 작동.',
    totalHours: 2.0,
    cost: 260,
    checklistItems: frequentChecklist.map((item) => ({ ...item, judgment: 'pass' })),
  },
  {
    id: 'insp-005',
    woNumber: 'INS-2026-0005',
    woType: 'frequent',
    craneId: 'crane-205',
    craneName: 'QC-205',
    siteId: 'dock-2',
    siteName: 'Dock No.2',
    scheduledDate: '2026-04-15',
    actualDate: null,
    assignedTo: '이태훈',
    performerType: 'internal',
    status: 'scheduled',
    priority: 'normal',
    result: null,
    checklistItems: frequentChecklist.map((item) => ({ ...item, judgment: null })),
  },
  {
    id: 'insp-006',
    woNumber: 'INS-2026-0006',
    woType: 'frequent',
    craneId: 'crane-301',
    craneName: 'BC-301',
    siteId: 'dock-in',
    siteName: 'Block Shop',
    scheduledDate: '2026-04-12',
    actualDate: '2026-04-12',
    assignedTo: '조범희',
    performerType: 'internal',
    status: 'completed',
    priority: 'normal',
    result: 'conditional',
    findings: 'Minor oil leak detected near reducer. Travel motor shows slight vibration increase.',
    findings_ko: '감속기 근처 경미한 오일 누유 발견. 주행 모터 진동 소폭 증가.',
    totalHours: 3.0,
    cost: 380,
    checklistItems: frequentChecklist.map((item, i) => ({
      ...item,
      judgment: i === 0 || i === 3 ? 'fail' : 'pass',
      severity: i === 0 ? 'minor' : i === 3 ? 'major' : 'normal',
      comment: i === 0 ? 'Oil leak at reducer seal' : i === 3 ? 'Vibration level above threshold' : undefined,
      actionRequired: i === 0 ? 'repair_needed' : i === 3 ? 'monitor' : 'none',
    })),
  },
  {
    id: 'insp-007',
    woNumber: 'INS-2026-0007',
    woType: 'frequent',
    craneId: 'crane-104',
    craneName: 'GC-104',
    siteId: 'dock-1',
    siteName: 'Dock No.1',
    scheduledDate: '2026-04-08',
    actualDate: null,
    assignedTo: '조범희',
    performerType: 'internal',
    status: 'overdue',
    priority: 'urgent',
    result: null,
    checklistItems: frequentChecklist.map((item) => ({ ...item, judgment: null })),
  },
  {
    id: 'insp-008',
    woNumber: 'INS-2026-0008',
    woType: 'frequent',
    craneId: 'crane-202',
    craneName: 'QC-202',
    siteId: 'dock-2',
    siteName: 'Dock No.2',
    scheduledDate: '2026-04-16',
    actualDate: null,
    assignedTo: '박순영',
    performerType: 'internal',
    status: 'scheduled',
    priority: 'normal',
    result: null,
    checklistItems: frequentChecklist.map((item) => ({ ...item, judgment: null })),
  },
];

export function getAllInspectionWOs(): InspectionWO[] {
  return allInspectionWOs;
}

export function getInspectionWOById(id: string): InspectionWO | undefined {
  return allInspectionWOs.find((w) => w.id === id);
}

export function getInspectionSummary(): InspectionSummary {
  const total = allInspectionWOs.length;
  const completed = allInspectionWOs.filter((w) => w.status === 'completed').length;
  const overdue = allInspectionWOs.filter((w) => w.status === 'overdue').length;
  const failed = allInspectionWOs.filter((w) => w.result === 'fail').length;
  return {
    totalScheduled: total,
    completed,
    overdue,
    failed,
    completionRate: total > 0 ? Math.round((completed / total) * 100) : 0,
  };
}
