import type { MaintenanceSummary, RepairWO } from './types';

const allRepairWOs: RepairWO[] = [
  {
    id: 'repair-001',
    woNumber: 'RPR-2026-0001',
    sourceType: 'inspection',
    sourceWoNumber: 'INS-2026-0001',
    craneId: 'crane-101',
    craneName: 'GC-101',
    siteId: 'dock-1',
    siteName: 'Dock No.1',
    componentName: 'Hoist Brake',
    componentName_ko: '호이스트 브레이크',
    failureType: 'mechanical',
    failureDescription: 'Brake pad worn to 60% of rated thickness. Replacement required within 30 days.',
    failureDescription_ko: '브레이크 패드 마모 60% 도달. 30일 이내 교체 필요.',
    repairLevel: 'minor',
    performerType: 'internal',
    assignedTo: '조범희',
    status: 'in_progress',
    priority: 'normal',
    scheduledStart: '2026-04-15T08:00:00',
    scheduledEnd: '2026-04-15T12:00:00',
    actualStart: '2026-04-15T08:30:00',
    actualEnd: null,
    downtimeHours: null,
    partsUsed: [
      { partId: 'part-br-001', partName: 'Brake Pad Set (Hoist)', qty: 1, unitCost: 480 },
    ],
    laborHours: null,
    laborCost: null,
    partsCost: 480,
    totalCost: null,
    rootCause: 'Normal wear after 18,200 hours of operation',
    rootCause_ko: '18,200시간 운용 후 정상 마모',
    correctiveAction: 'Replace brake pad set',
    correctiveAction_ko: '브레이크 패드 세트 교체',
    preventiveAction: 'Schedule brake inspection every 3,000 operating hours',
    preventiveAction_ko: '3,000 운용시간마다 브레이크 점검 일정 수립',
  },
  {
    id: 'repair-002',
    woNumber: 'RPR-2026-0002',
    sourceType: 'breakdown',
    craneId: 'crane-104',
    craneName: 'GC-104',
    siteId: 'dock-1',
    siteName: 'Dock No.1',
    componentName: 'Travel Motor (Left)',
    componentName_ko: '주행 모터 (좌측)',
    failureType: 'electrical',
    failureDescription: 'Travel motor overheating alarm triggered. Motor temperature reached 92°C. Crane stopped automatically.',
    failureDescription_ko: '주행 모터 과열 알람 발생. 모터 온도 92°C 도달. 크레인 자동 정지.',
    repairLevel: 'major',
    performerType: 'third_party',
    assignedTo: 'M&S Corp.',
    status: 'waiting_parts',
    priority: 'high',
    scheduledStart: '2026-04-16T08:00:00',
    scheduledEnd: '2026-04-18T17:00:00',
    actualStart: null,
    actualEnd: null,
    downtimeHours: 36,
    partsUsed: [],
    laborHours: null,
    laborCost: null,
    partsCost: null,
    totalCost: null,
    rootCause: 'Motor winding insulation degradation due to prolonged high-temperature operation',
    rootCause_ko: '장시간 고온 운전으로 인한 모터 권선 절연 열화',
    correctiveAction: 'Replace motor winding / Full motor overhaul',
    correctiveAction_ko: '모터 권선 교체 / 전체 모터 오버홀',
    preventiveAction: 'Install temperature monitoring relay, improve ventilation',
    preventiveAction_ko: '온도 모니터링 릴레이 설치, 환기 개선',
  },
  {
    id: 'repair-003',
    woNumber: 'RPR-2026-0003',
    sourceType: 'inspection',
    sourceWoNumber: 'INS-2026-0006',
    craneId: 'crane-301',
    craneName: 'BC-301',
    siteId: 'dock-in',
    siteName: 'Block Shop',
    componentName: 'Travel Reducer',
    componentName_ko: '주행 감속기',
    failureType: 'mechanical',
    failureDescription: 'Oil leak detected at reducer output shaft seal. Vibration level 140% above baseline.',
    failureDescription_ko: '감속기 출력축 씰에서 오일 누유 발견. 진동 수준 기준치 대비 140% 초과.',
    repairLevel: 'minor',
    performerType: 'internal',
    assignedTo: '정종민',
    status: 'in_progress',
    priority: 'normal',
    scheduledStart: '2026-04-14T09:00:00',
    scheduledEnd: '2026-04-14T15:00:00',
    actualStart: '2026-04-14T09:15:00',
    actualEnd: null,
    downtimeHours: null,
    partsUsed: [
      { partId: 'part-seal-001', partName: 'Output Shaft Oil Seal', qty: 2, unitCost: 45 },
      { partId: 'part-oil-001', partName: 'Gear Oil (20L)', qty: 1, unitCost: 120 },
    ],
    laborHours: null,
    laborCost: null,
    partsCost: 210,
    totalCost: null,
  },
  {
    id: 'repair-004',
    woNumber: 'RPR-2026-0004',
    sourceType: 'breakdown',
    craneId: 'crane-303',
    craneName: 'BC-303',
    siteId: 'dock-in',
    siteName: 'Block Shop',
    componentName: 'Main Controller',
    componentName_ko: '주 제어기',
    failureType: 'control',
    failureDescription: 'PLC communication error. Crane non-operational. Emergency stop cannot be reset.',
    failureDescription_ko: 'PLC 통신 오류. 크레인 운전 불가. 비상 정지 해제 불가.',
    repairLevel: 'major',
    performerType: 'third_party',
    assignedTo: 'Liebherr Service',
    status: 're_inspection',
    priority: 'emergency',
    scheduledStart: '2026-04-13T06:00:00',
    scheduledEnd: '2026-04-14T18:00:00',
    actualStart: '2026-04-13T07:00:00',
    actualEnd: '2026-04-14T16:00:00',
    downtimeHours: 33,
    partsUsed: [
      { partId: 'part-plc-001', partName: 'PLC Module (CPU)', qty: 1, unitCost: 3200 },
      { partId: 'part-cable-001', partName: 'Communication Cable Set', qty: 1, unitCost: 180 },
    ],
    laborHours: 12,
    laborCost: 2400,
    partsCost: 3380,
    totalCost: 5780,
    rootCause: 'PLC CPU module failure due to power surge',
    rootCause_ko: '전원 서지로 인한 PLC CPU 모듈 고장',
    correctiveAction: 'Replaced PLC CPU module and communication cables',
    correctiveAction_ko: 'PLC CPU 모듈 및 통신 케이블 교체',
    preventiveAction: 'Install surge protector, schedule annual PLC diagnostics',
    preventiveAction_ko: '서지 보호기 설치, 연간 PLC 진단 일정 수립',
    reInspectionResult: null,
  },
  {
    id: 'repair-005',
    woNumber: 'RPR-2026-0005',
    sourceType: 'preventive',
    craneId: 'crane-201',
    craneName: 'QC-201',
    siteId: 'dock-2',
    siteName: 'Dock No.2',
    componentName: 'Wire Rope (Aux Hoist)',
    componentName_ko: '와이어 로프 (보조 호이스트)',
    failureType: 'mechanical',
    failureDescription: 'Wire rope reached scheduled replacement interval (8,000 hours). Preventive replacement.',
    failureDescription_ko: '와이어 로프 교체 주기(8,000시간) 도달. 예방 교체 실시.',
    repairLevel: 'minor',
    performerType: 'internal',
    assignedTo: '박순영',
    status: 'completed',
    priority: 'normal',
    scheduledStart: '2026-04-10T08:00:00',
    scheduledEnd: '2026-04-10T14:00:00',
    actualStart: '2026-04-10T08:00:00',
    actualEnd: '2026-04-10T13:30:00',
    downtimeHours: 5.5,
    partsUsed: [
      { partId: 'part-wr-002', partName: 'Wire Rope 28mm 6x37 (200m)', qty: 1, unitCost: 1850 },
    ],
    laborHours: 5.5,
    laborCost: 715,
    partsCost: 1850,
    totalCost: 2565,
    rootCause: 'Scheduled preventive replacement',
    rootCause_ko: '계획된 예방 교체',
    correctiveAction: 'Replaced wire rope per PM schedule',
    correctiveAction_ko: 'PM 일정에 따라 와이어 로프 교체',
    preventiveAction: 'Next replacement scheduled at 16,000 hours',
    preventiveAction_ko: '다음 교체: 16,000시간',
    reInspectionResult: 'pass',
  },
  {
    id: 'repair-006',
    woNumber: 'RPR-2026-0006',
    sourceType: 'breakdown',
    craneId: 'crane-205',
    craneName: 'QC-205',
    siteId: 'dock-2',
    siteName: 'Dock No.2',
    componentName: 'Hoist Inverter',
    componentName_ko: '호이스트 인버터',
    failureType: 'electrical',
    failureDescription: 'Inverter fault alarm. Hoist function inoperative. Error code: ERR-INV-007.',
    failureDescription_ko: '인버터 고장 알람. 호이스트 기능 불가. 오류 코드: ERR-INV-007.',
    repairLevel: 'major',
    performerType: 'third_party',
    assignedTo: 'Konecranes Service',
    status: 'received',
    priority: 'high',
    scheduledStart: '2026-04-16T08:00:00',
    scheduledEnd: '2026-04-17T17:00:00',
    actualStart: null,
    actualEnd: null,
    downtimeHours: null,
    partsUsed: [],
    laborHours: null,
    laborCost: null,
    partsCost: null,
    totalCost: null,
  },
];

export function getAllRepairWOs(): RepairWO[] {
  return allRepairWOs;
}

export function getRepairWOById(id: string): RepairWO | undefined {
  return allRepairWOs.find((w) => w.id === id);
}

export function updateRepairStatus(id: string, status: RepairWO['status']): boolean {
  const idx = allRepairWOs.findIndex((w) => w.id === id);
  if (idx === -1) return false;
  allRepairWOs[idx] = { ...allRepairWOs[idx], status };
  return true;
}

export function addRepairWO(wo: RepairWO): void {
  allRepairWOs.unshift(wo);
}

export function getMaintenanceSummary(): MaintenanceSummary {
  return {
    inProgress: allRepairWOs.filter((w) =>
      ['in_progress', 're_inspection'].includes(w.status),
    ).length,
    waitingParts: allRepairWOs.filter((w) => w.status === 'waiting_parts').length,
    emergency: allRepairWOs.filter((w) => w.priority === 'emergency').length,
    avgMttrHours: 8.4,
    avgMtbfDays: 42,
  };
}
